### ISSUE TITLE
can not start on windows

### ISSUE THREAD

**Issue by lostfile** [mwarning/KadNode#100]
![err](https://user-images.githubusercontent.com/11745567/55292760-776e4200-53a3-11e9-94dd-594d9f035051.png)

**Comment by lostfile** [comment]
![pop](https://user-images.githubusercontent.com/11745567/55292804-dcc23300-53a3-11e9-8351-5c7ee749e733.png)

**Comment by mwarning** [comment]
Looks like Windows needs some extra handling to get ipv6 local peer discovery going. IPv4 might work.

**Comment by mwarning** [comment]
Is kadnode already running? Try to execute `kadnode-ctl` and see if you can reach the instance.

**Comment by mwarning** [comment]
Did kadnode exit on its own `kadnode -6`? That should not happen.

**Comment by lostfile** [comment]
kadnode-ctl was missing when i compiled it

**Comment by lostfile** [comment]
$ kadnode-ctl status
Failed to connect to '/tmp/kadnode/kadnode_cmd.sock': No such file or directory

**Comment by mwarning** [comment]
ah, on windows kadnode-ctl cannot work (because unix sockets are not supported there)

**Comment by mwarning** [comment]
I will look into it tomorrow.

**Comment by mwarning** [comment]
Sorry it tool so long (just a few years..), but right now Windows is not tested / supported.
