### ISSUE TITLE
daemon crashes on resovle

### ISSUE THREAD

**Issue by lostfile1** [mwarning/KadNode#101]
![Screenshot from 2019-09-18 20-00-44](https://user-images.githubusercontent.com/41842361/65196875-086acf80-da4f-11e9-8883-785effbaf420.png)

**Comment by mwarning** [comment]
hi, do you have to happen a stack trace or something to locate the problem?

**Comment by mwarning** [comment]
I will try to do some debugging next week.

Btw., what version do you use? Or current git master?

**Comment by lostfile1** [comment]
i think i was using the master version

**Comment by mwarning** [comment]
ok, thanks. Anything I can do to provoke the error?

**Comment by lostfile1** [comment]
i was using it in vbox i think and i tried to ping the hashed domain and it just bummed out on me

**Comment by mwarning** [comment]
I should definitely investigate that problem before the next release.

**Comment by mwarning** [comment]
I have fixed a few possible causes. Could you please test again?

**Comment by lostfile1** [comment]
I will

**Comment by lostfile1** [comment]
And it works 
![15812846741806229617684759555666](https://user-images.githubusercontent.com/41842361/74110546-7da08380-4b5b-11ea-9ca9-5dc71e869f07.jpg)
![15812846937859104969786097681632](https://user-images.githubusercontent.com/41842361/74110552-885b1880-4b5b-11ea-82c7-36696b6c3ba9.jpg)

**Comment by lostfile1** [comment]
works on my site to lol
![Screenshot from 2020-02-09 16-47-38](https://user-images.githubusercontent.com/41842361/74110609-061f2400-4b5c-11ea-8ee3-5812c7f6e29c.png)

**Comment by mwarning** [comment]
Awesome! :-)
