### ISSUE TITLE
keeps trying to uninstall debian package

### ISSUE THREAD

**Issue by lostfile1** [mwarning/KadNode#102]
apt keeps thinking the debian package i built is broken because it has a unmet dep
 Depends: libmbedtls10 (>= 2.4.2) but it is not installable

**Comment by mwarning** [comment]
thank for reporting, I will look into it.

**Comment by mwarning** [comment]
This should fix it: https://github.com/mwarning/KadNode/commit/7ca5983faf0505460f3d53cffe0f747e11f74b9e
