### ISSUE TITLE
can not build in cygwin

### ISSUE THREAD

**Issue by lostfile1** [mwarning/KadNode#103]
![Untitled](https://user-images.githubusercontent.com/41842361/74679849-f2dc0c00-518c-11ea-948e-459d1878d57e.png)

**Comment by lostfile1** [comment]
well i fixed that problem how ever when i complie it it save kadnode-cli as a system file and not an exe

**Comment by mwarning** [comment]
Hi, I haven't tried to compile the code for windows in years and gave to admit that I do not remember anymore how I got an exe file. Maybe it works if you rename it?

**Comment by mwarning** [comment]
You have probably seen my documentation: https://github.com/mwarning/KadNode/tree/master/windows

**Comment by mwarning** [comment]
The latest release has not been tested Windows and there are no packages. Right now Windows is not supported. But I will give it a try in the future and provide binaries.
