### ISSUE TITLE
here's an example address you can use

### ISSUE THREAD

**Issue by lostfile1** [mwarning/KadNode#105]
my node is currently not using any trackers so i dont know if you can connect to it plus this is self hosed so its not a 100% reliable but heres an address that will take to to my text board
http://45qh436joj2vrphg28alsnreg18f0vmd42ufeg27ud0v4dj3f670.p2p/
also keep in mind that the latency is very high because i also have i2pd and tor running on it
and its only a rasberrypi

**Comment by mwarning** [comment]
hm, so you mean it resolved to the wrong IP address? If that is the case, what does `kadnode-ctl list searches` say?

**Comment by lostfile1** [comment]
i think it could have some thing to with my resolver
![Screenshot from 2020-03-07 10-37-22](https://user-images.githubusercontent.com/41842361/76146331-c1ee4900-605f-11ea-80fd-3ac63562d5fc.png)

**Comment by mwarning** [comment]
I looks like that KadNode has not found an IP address yet (neither can I from my computer).
What does `kadnode-ctl list annoucements` say?

**Comment by lostfile1** [comment]
himm maybe i could make a new bob key
![Untitled](https://user-images.githubusercontent.com/41842361/76147243-4218ac80-6068-11ea-8e08-8dfcb25dce74.png)

**Comment by lostfile1** [comment]
i could have sworn i had this working fine before i dont know what happend

**Comment by lostfile1** [comment]
okay it fixes its self after i do a kadnode-ctl lookup address with out the .p2p

**Comment by mwarning** [comment]
That sounds like a bug. I will test it. But probably not today.

**Comment by mwarning** [comment]
btw., what version of KadNode do you use?

**Comment by lostfile1** [comment]
im using the latest version

**Comment by mwarning** [comment]
There is a new release. Let me know if the bug is still there for you and create a new ticket if needed. Thank you.
