### ISSUE TITLE
natpmp upnp features ?

### ISSUE THREAD

**Issue by uneame** [mwarning/KadNode#106]
Hello, I'm trying to use kadnode to make my laptop discoverable on the net, my laptop (ubuntu 20.04) connect on the android hotspot. 
I uncoment natpmp upnp feature in the Makefile and did the build for debian, the build raise no errors and lintian 2 warnings

**$ lintian kadnode_2.3.0-1_amd64.deb
W: kadnode: new-package-should-close-itp-bug
W: kadnode: package-name-doesnt-match-sonames libnss-kadnode2**

But once the package installed, a call to version don't show the new features
**$ kadnode --version
KadNode v2.3.0 ( bob cmd lpd nss tls )**

Did I miss something ?

**Comment by mwarning** [comment]
I've checked the code. The Debian package was compiled without natpmp/upnp (https://github.com/mwarning/KadNode/blob/master/debian/rules#L5). But the package pulls in the dependencies for this nevertheless.

You could change the rules to `export FEATURES="tls bob lpd cmd nss natpmp upnp"` and compile the debian package again.

**Comment by uneame** [comment]
Thank you,
It work perfectly
**$ kadnode --version
KadNode v2.3.0 ( bob cmd lpd natpmp nss tls upnp )**

**Comment by mwarning** [comment]
Awesome!
