### ISSUE TITLE
Cannot build on Cygwin64.

### ISSUE THREAD

**Issue by byaeger** [mwarning/KadNode#107]
Hello! Hope this is a bug and not my lack of knowlege of C lol.
I run the following command to build on windows:

FEATURES="bob tls dns lpd" make

And this is what I get:

cc -Os -Wall -Wwrite-strings -pedantic -std=gnu99 -I/usr/local/include  -DLPD -DBOB -DDNS -DTLS -c -o build/ext-lpd.o src/ext-lpd.c
src/ext-lpd.c: In function ‘join_mcast’:
src/ext-lpd.c:79:25: error: ‘AF_PACKET’ undeclared (first use in this function)
   79 |   if (is_valid_ifa(ifa, AF_PACKET)) {
      |                         ^~~~~~~~~
src/ext-lpd.c:79:25: note: each undeclared identifier is reported only once for each function it appears in
src/ext-lpd.c: In function ‘send_mcasts’:
src/ext-lpd.c:120:54: error: ‘AF_PACKET’ undeclared (first use in this function)
  120 |   } else if (family == AF_INET6 && is_valid_ifa(ifa, AF_PACKET)) {
      |                                                      ^~~~~~~~~
make: *** [Makefile:81: build/ext-lpd.o] Error 1

Any help is appreciated.

**Comment by mwarning** [comment]
Should compile now.
