### ISSUE TITLE
An odd bug

### ISSUE THREAD

**Issue by lostfile1** [mwarning/KadNode#109]
When I generate a bob key  Instead of having .p2p at the end of it it prints out .(null)  Only this is on ubuntu 20.04 and this is the version of kadnode i just compiled from github

**Comment by lostfile1** [comment]
![Screenshot from 2020-09-29 16-54-10](https://user-images.githubusercontent.com/41842361/94614631-7b1ea580-0274-11eb-8094-c028b6b78d7e.png)

**Comment by mwarning** [comment]
hi, is that a release version of kadnode? Or the latest master? thanks for reporting. I will take a look later.

**Comment by mwarning** [comment]
nvm., I see the error.

**Comment by mwarning** [comment]
The bug fix is very simple, but I do not know if it breaks something the way I like to fix it..

**Comment by mwarning** [comment]
I do not remember this bugs cause anymore. But I also do not see it anymore. Closing for now.
