### ISSUE TITLE
onion like domain with ed25519

### ISSUE THREAD

**Issue by stokito** [mwarning/KadNode#113]
It would be great to have a domain that in case of blocking can be easily switched to a Tor onion by just replacing the .p2p in the end to .onion.
Also if I running a Single onion service on the same machine then I can just reuse the same keys.

In order to do that the domain must be generated with ed25519 which wasn't supported by the mbedtls.
But now it seems like the curve is supported
https://github.com/Mbed-TLS/mbedtls/search?q=ed25519

Could you please confirm that it's possible now to use it?

Also the onion v3 domains have 2 bytes for checksum plus a byte for version.

**Comment by mwarning** [comment]
Interesting to know. I will take a look.

**Comment by mwarning** [comment]
It would be nice to swtich to ED25519, but it seems the implementation in mbedtls is not complete (enough). I do not find an entry here: https://github.com/Mbed-TLS/mbedtls/blob/development/library/ecp.c#L404

**Comment by stokito** [comment]
oh, that's sad. Thank you for the answer!
I'm also interested in your opinion about if the idea of having interoperable domains between tor onion and KadNode makes any sense to you.
Thus if the KadNode is not installed a user still can open a link but just by using a Tor browser.
Also the onion domains are shorter because they are Base32 encoded. Why the KadNode uses hex?

Initially my goal was to create a Dynamic DNS server that doesn't needs for a manual registration step.
And idea was to generate an onion domain. To update a DNS record just send a signed request with privkey. See https://github.com/yurt-page/dyndns-onion

Then I came to idea to also use DHT i.e. the same as KadNode :) And the KadNode is perfect!
But the main difference is that I want to anybody who even doesn't have a kadnode installed to be able to open such sites. So know I think to setup a KadNode on my jkl.mn server and make it as NS for all subdomains.
But the resolution via DHT would be long. So still think to just implement a simple DNS record update with a plain GET request. So that the DHT lookup in KadNode network will be performed only if the DNS record wasn't found in my database.
If my jkl.mn DNS server will be blocked or disappears users still can install the KadNode to get to a site.

While doing a research I also found GNUnet Name System which is also DHT based but it looks so complicated so that I'll just leave it alone.

The KadNode seems so small so that may be included into OpenWrt by default. Like imagine that any OpenWrt device already have some domain out of the box. That would be cool.

**Comment by mwarning** [comment]
Hi @stokito 

if we can have some interoperability between TOR and KadNode addresses, then that would be nice.
Anyway, the addresses that KadNode use are already in Base32. In the source code it says base32hex, which is confusing, I will fix that. :-)

> While doing a research I also found GNUnet Name System which is also DHT based but it looks so complicated so that I'll just leave it alone.

You are not the only one who has this impression.

Is there anything else that need to be done?

**Comment by stokito** [comment]
Thank you

**Comment by stokito** [comment]
Sorry for rising the old topic. I just want let you know that openwrt has usign utility and internally it has the [ed25519](https://github.com/openwrt/usign/blob/master/ed25519.c).


We can generate a key pair:

   usign -G -s onion.key -p onion.pub

Then the onion.pub will look like:
RWSNGBSrjIP7GAZN409X3/x2vi+4e2BpScIQcarK8bP/yyEesp7h0DxH

First digits are [fingerprint of the key](https://github.com/openwrt/usign/blob/master/main.c#L283).

So basically it's possible to generate the ed25519 domain even without the OpenSSL on a router.
Except of a domain generation and TLS verification does the mbedtls is used for anything else? SHA1? It looks like the KadNode can have own code just for the DHT client.
I saw that you extracted [dhtd](https://github.com/mwarning/dhtd) from KadNode and it doesn't have any TLS dependencies. 

For me this is a good news because I can write a simple DDNS client in shell that will use the usign to sign an IP and then use uclient-fetch to update domain's A record.

Yeah, and we can also use a Dropbear to generate an ed25519 key pair. But no signing there.

**Comment by mwarning** [comment]
hi,

yes, I think using ed25519.c migth be possible. But it is hard to find time.

> I saw that you extracted [dhtd](https://github.com/mwarning/dhtd) from KadNode and it doesn't have any TLS dependencies.
>
>For me this is a good news because I can write a simple DDNS client in shell that will use the usign to sign an IP and then >use uclient-fetch to update domain's A record.

Yes, that is the plan. Let users use the DHT from the command line. But development is in phases. I do not have an ETA for when it is usable.

**Comment by mwarning** [comment]
I have fixed a few issues in DHTd. It might need polishing, but otherwise it should be usable.
