### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by melroy89** [mwarning/KadNode#128]
Latest release is from 2020. Why not create a new one? 🥳

**Comment by mwarning** [comment]
hi there. The problem is time and too many other projects.
The other major hurdly is that mbedtls made some key field private and now I need to figure out if I can workaround those limitations, need an additional crypto library or cut away the affected feature... :/

**Comment by melroy89** [comment]
I see. Fully understand. Maybe create an issue at https://github.com/Mbed-TLS/mbedtls and hopefully they solve it again?

**Comment by Neustradamus** [comment]
Dear @mwarning,

The latest version is 2.3.0 (2020-02-10):
- https://github.com/mwarning/KadNode/releases

Maybe you can transfer this repository in an organization to have the development and add new people?

@gstrauss has done a PR to add mbedtls-3.x support:
- https://github.com/mwarning/KadNode/pull/130

Thanks in advance.

**Comment by mwarning** [comment]
Hi, I would like to do some tests before issuing a new release. There are also a few changes I have on my disk. I will likely be able to do it this week.

**Comment by mwarning** [comment]
There are problems loading key files from disk (--bob-load-key) and I haven't figured out the issue yet. Also, I want to distinguish the key types somehow.

**Comment by mwarning** [comment]
There seems to be a minor bug in the (bob) authentication code. Otherwise it looks good.

**Comment by mwarning** [comment]
A new release (2.4.0) has been published.
