### ISSUE TITLE
Build is failed on the latest Ubuntu Oracular:  UPNP_GetValidIGD()

### ISSUE THREAD

**Issue by stokito** [mwarning/KadNode#131]
```
src/upnp.c: In function ‘upnp_handler’:
src/upnp.c:137:20: error: too few arguments to function ‘UPNP_GetValidIGD’
  137 |         } else if (UPNP_GetValidIGD(devlist, &handle->urls, &handle->data,
      |                    ^~~~~~~~~~~~~~~~
In file included from src/upnp.h:5,
                 from src/upnp.c:10:
/usr/include/miniupnpc/miniupnpc.h:122:1: note: declared here
  122 | UPNP_GetValidIGD(struct UPNPDev * devlist,
      | ^~~~~~~~~~~~~~~~

```

https://launchpadlibrarian.net/755854326/buildlog_ubuntu-oracular-amd64.kadnode_2.3.0-0~202410251254~ubuntu24.10.1_BUILDING.txt.gz

**Comment by mwarning** [comment]
I am changing the code a lot right now and will fix these things soon. Please be patient. Thank you. :)

**Comment by mwarning** [comment]
The code should compile now. But now I need to test the functionality and fix any bugs.

**Comment by mwarning** [comment]
Not yet. I have to check basic functionality first. Probably tomorrow.
