### ISSUE TITLE
Config option --ipv4 and --ipv6 cause an error: Network mode already set

### ISSUE THREAD

**Issue by stokito** [mwarning/KadNode#133]

**Comment by mwarning** [comment]
`--ipv4` enables IPv4 only mode. `--ipv6` enables IPv6 only mode.  They are mutually exclusive.
But the help text might be confusing since the default says IPv4+IPv6.

What do you think we should make that clearer?

**Comment by mwarning** [comment]
Then  I have fixed that problem by now.
