### ISSUE TITLE
--fwd-disable causes segfault 

### ISSUE THREAD

**Issue by stokito** [mwarning/KadNode#143]
I uncommented the `--fwd-disable` in the config and the KadNode crashed on start:

    sendnewportmappingrequest (libnatpmp.so.1 + 0x14da)
    __libc_start_call_main
    __libc_start_main_impl

So for some reason the `--fwd-disable` doesn't stops the KadNode from trying to call the natpmp to create a port forwarding.

I tried it with the SystemD so the `journalctl -u kadnode -f -n 300` shows:

```
kadnode.service: Main process exited, code=dumped, status=11/SEGV
kadnode.service: Failed with result 'core-dump'.
Stopped P2P DNS resolver.
Starting P2P DNS resolver...
kadnode.service: New main PID 48627 does not exist or is a zombie.
kadnode.service: Failed with result 'protocol'.
Failed to start P2P DNS resolver.
kadnode.service: Scheduled restart job, restart counter is at 1.
```

After 5 attempts to restart it stops to try.
The `systemctl status kadnode` shows: `Active: failed (Result: protocol)`.

With the `coredumpctl` we may see the dump and even debug it.

**Comment by mwarning** [comment]
@stokito yes, a new release would be a good idea.
Let's test the functionality on all platforms we care about and then create an official release.
