### ISSUE TITLE
dnsmasq integration fail

### ISSUE THREAD

**Issue by stargieg** [mwarning/KadNode#39]
I have a dnsmasq startup error with 
```uci add_list dhcp.@dnsmasq[0].server='/p2p/localhost#5353'```
bad address at line 12 of /var/etc/dnsmasq.conf
line 12
```server=/p2p/localhost#3535 ```
I have replace the hostname with ip addr. Then this works fine.
```uci add_list dhcp.@dnsmasq[0].server='/p2p/::1#5353'```

**Comment by mwarning** [comment]
ok, we should change that.
