### ISSUE TITLE
feature request ifname list

### ISSUE THREAD

**Issue by stargieg** [mwarning/KadNode#44]
support Interface list in ifname config option.
e.g. Listen on lan and wifi but not on wan.

**Comment by mwarning** [comment]
This was on my list.. But I felt the demand was not big enough to justify the effort. Merge requests are welcome.

**Comment by mwarning** [comment]
The feature is still not supported and even --ifname does not quite right. Patches to show the way are welcome.

**Comment by mwarning** [comment]
KadNode would be able to support to bind to a single IPv4 and IPv6 address instead of a list of interfaces. Would that be sufficient?

**Comment by mwarning** [comment]
Closing for now. Please create a new ticket  if you need an option to bind the DHT to a specific/static IP address.

**Comment by stargieg** [comment]
> KadNode would be able to support to bind to a single IPv4 and IPv6 address instead of a list of interfaces. Would that be sufficient?

I have created a firewall rule for outgoing dht traffic via the wan interface. Its working.
