### ISSUE TITLE
global key exchange based on keybase

### ISSUE THREAD

**Issue by atommixz** [mwarning/KadNode#47]
https://keybase.io/

Maybe you can use it for make kadnode is global dns resolution system?

**Comment by atommixz** [comment]
I have invite for you

**Comment by atommixz** [comment]
or maybe we can use sks-keyservers peering network for it 
https://sks-keyservers.net/status/
https://bitbucket.org/skskeyserver/sks-keyserver/wiki/Peering

**Comment by atommixz** [comment]
https://github.com/andres-erbsen/dename

**Comment by mwarning** [comment]
Sound very interesting.
But I need to find some free time first. :|

**Comment by atommixz** [comment]
keybase and dename required invite (but dename site is offline for me). Keybase looks like proprietary server and federated model, dename looks like fully open source (I'm not sure about server side) and decentralized model, but main site is offline and invite required.

But gpg keyservers looks interesting for key exchange. Its very popular, decentralized and should be open source for server side.

**Comment by mwarning** [comment]
keybase and dename are about people. KadNode is simply about finding an IP-adress. There is overlap, but for now I do not have the time to think much about common approaches and goals.
