### ISSUE TITLE
how to configure?

### ISSUE THREAD

**Issue by axxName** [mwarning/KadNode#48]
I can't understand how to configure:

first node config:
--peerfile /etc/kadnode/peers.txt
--value-id s17.p2p
--auth-add-skey s17.p2p:c84995c206b6fd702d9af43497faa4fb10e3e847fe068350a5fdc851d84ed72690d59cdde52e2d858746efd4c0e5f14ad8c5d80b7f6b879cbcd4ed45142ffa4b
# public key: 90d59cdde52e2d858746efd4c0e5f14ad8c5d80b7f6b879cbcd4ed45142ffa4b
# secret key: c84995c206b6fd702d9af43497faa4fb10e3e847fe068350a5fdc851d84ed72690d59cdde52e2d858746efd4c0e5f14ad8c5d80b7f6b879cbcd4ed45142ffa4b

---
# kadnode-ctl status

Version: KadNode v1.0.0 ( lpd auth cmd nss natpmp upnp )
DHT id: 7832701de2acd9b972878cdb0edad3e68c5336f2
DHT bound to: 0.0.0.0:6881 / <any device>
DHT Nodes: 186 (107 good) (IPv4)
DHT Storage: 0 (max 16384), 0 peers (max 2048 per storage)
DHT Searches: 0 active, 1 completed (max 1024)
DHT Blacklist: 4 (max 10)
DHT Values to announce: 1
# ping s17.p2p

  -- Works fine on this  host (first node)!!!

second node config:
--peerfile /etc/kadnode/peers.txt
--auth-add-pkey s17.p2p:90d59cdde52e2d858746efd4c0e5f14ad8c5d80b7f6b879cbcd4ed45142ffa4b
# public key: 90d59cdde52e2d858746efd4c0e5f14ad8c5d80b7f6b879cbcd4ed45142ffa4b
# secret key: c84995c206b6fd702d9af43497faa4fb10e3e847fe068350a5fdc851d84ed72690d59cdde52e2d858746efd4c0e5f14ad8c5d80b7f6b879cbcd4ed45142ffa4b

---
# kadnode-ctl status

Version: KadNode v1.0.0 ( lpd auth cmd nss natpmp upnp )
DHT id: b632de370fa4f92c4e018e0996407e5ac3a390e9
DHT bound to: 0.0.0.0:6881 / <any device>
DHT Nodes: 136 (69 good) (IPv4)
DHT Storage: 0 (max 16384), 0 peers (max 2048 per storage)
DHT Searches: 0 active, 1 completed (max 1024)
DHT Blacklist: 0 (max 10)
DHT Values to announce: 0
# ping s17.p2p

ping: unknown host    !!!!

What is wrong?

**Comment by mwarning** [comment]
KadNode has probably not been installed onto the system yet (use "make install"). Try "kadnode-ctl lookup s17.p2p" to see if resolving works so far (first call will start lookup, afterwards a result may be seen).

**Comment by axxName** [comment]
My config is correct?
Both nodes behind NAT. Does it matter?
,,
\#grep kadnode /etc/nsswitch.conf
hosts:          files kadnode dns

**Comment by mwarning** [comment]
both nodes behind won't work, unless one of the routers have support for natpmp (and KadNode has support enabled). Or use IPv6 mode.

**Comment by axxName** [comment]
ОК. I understand how it works.
It works now for me under linux.
But, under Windows it works only inside Kadnode daemon:
>kadnode-ctl.exe lookup s17.p2p
  <finds my ip address>

But, no response from DNS (53) port
> nslookup
> server 127.0.0.1
Default server: 127.0.0.1
Address: 127.0.0.1#53
> s17.p2p
;; connection timed out; no servers could be reached

p.s.
kadnode build with dns code, and daemon started with option   --dns-port 53

**Comment by mwarning** [comment]
@axxName Maybe the installer is broken on Windows. But it may depend on the Windows Version. What Windows version do you use?

**Comment by mwarning** [comment]
@axxName Maybe the installer is broken on Windows. But it may depend on the Windows Version. What Windows version do you use?

And nice to hear that you got it working.

**Comment by axxName** [comment]
Windows 7 Home Basic (32)
Windows 7 Ultimate (64)
the same result with kadnode dns option in Linux

**Comment by mwarning** [comment]
That worked for me once. But I had not tested in for quite some time. I would need to setup my Testenvironment.

**Comment by axxName** [comment]
would be grateful if it will work

**Comment by axxName** [comment]
I think I found error in your code about DNS response.
May be I am wrong, but now I see nslookup resolves


`diff --git a/src/ext-dns.c b/src/ext-dns.c
index 956a4ad..474309a 100644
--- a/src/ext-dns.c
+++ b/src/ext-dns.c
@@ -500,7 +500,7 @@ int dns_setup_msg( struct Message *msg, IP addrs[], size_t addrs_num, const char
                /* Assume AAAA or A Record Type */
                for( i = 0; i < addrs_num; i++, c++ ) {
                        setAddressRecord( &msg->answers[c], qName, &addrs[i] );
-                       msg->arCount++;
+                       msg->anCount++;
                }
        }
`
Can you confirm my assumption?

**Comment by mwarning** [comment]
@axxName You are right, the answer to an address record should be counted ad an answer record (anCount), not additional information record (arCount).
Thanks a lot!

Anyway, I forgot about this ticket - too much stuff to do. :(
