### ISSUE TITLE
store transaction detail

### ISSUE THREAD

**Issue by debarko** [mwarning/KadNode#49]
Hi

I was wondering instead of sending back an IP as a result of a DNS request, can it send back a transaction number from bitcoin blockchain?

Or maybe with a few mods to this codebase, can we change it to do so?

**Comment by mwarning** [comment]
Well, the API of the operating system only transmits IPv4/IPv6 addresses from the backend (e.g. KadNode) to the application (e.g. the browser). You you try to put a bitcoin address into an IPv6 address. It is doable, but you would need to use the js library in the browser to make use of the bitcoin address and not to try treat it as an IPv6 address.

**Comment by debarko** [comment]
Ofcourse. The plan is to put an extension in all major browsers which will
be able to interpret these messages. Can you please guide me to the piece
of code where it handles the above mentioned handlers.


-----
Best Regards,
Debarko De <http://about.me/debarko>

**Comment by mwarning** [comment]
@debarko hm, I thought about it, I might be wrong. I have to think about this some more.

**Comment by mwarning** [comment]
Sending back a bitcoin transaction number would involve a lot of hacks. That is way I will close this ticket for now.
I rather would like to use a DHT that does not act as a storage (that is an extra feature of the DHTs used for BitTorrent).
