### ISSUE TITLE
Not working without modification on the latest Ubuntu/Linux Mint

### ISSUE THREAD

**Issue by EternityForest** [mwarning/KadNode#55]
Probably a fairly minor issue, but it appears that libsodium13 and libminiupnpc5 are both gone in the latest Linux Mint repository, but the program will install, run, and connect if I change the Debian control file to reference libsodium18 and libminiupnpc10 instead, but I'm not sure what the actual difference between the packages is so it might not "actually" be working.

If the packages really are mostly the same, it would be fairly simple to fix, but I'm not sure what the difference between them actually is.

This looks like it could be great for IoT applications, home automation and chat programs if it ever really went mainstream.

**Comment by mwarning** [comment]
I think it is pretter safe to use libsodium18 and libminiupnpc10.
Do you like to make a merge request?

Thought I do not have much time, I think this program has some potential.
I also started to create chat plugin for pidgin (a chat client), that let you connect to some IP address or domain name like foobar.p2p (!). Simple as that, that can be used with KadNode.

Anyway, there are few issues with KadNode:
- resolve speed (there might be modifications possible to allow ~1sec lookups)
- the link format is for crypto keys is not ubiquitous
- local peer discovery might be broken, I have some untested fixes I need to polish

**Comment by axxName** [comment]
I've made pull request.
But in current debian 8 jessie - libsodium13 used
