### ISSUE TITLE
dns lookups

### ISSUE THREAD

**Issue by axxName** [mwarning/KadNode#57]
There is a problem in Windows
first DNS server points to Google(8.8.8.8)
second DNS server - Kadnode service(127.0.0.1)

> nslookup myserver.p2p

google cant'resolve this address.
then nslookup stops.

if we setup first DNS Kadnode (127.0.0.1)  - only our  .p2p hosts resolvable
other internet - NO.

I think  some getHostbyName() code needed to resolve addresses from Internet DNS servers.

**Comment by mwarning** [comment]
The install script for Windows should put Kadnode as the first DNS server.
@axxName Is 8.8.8.8 used as first DNS server, or does Windows prefer 8.8.8.8?

Anyway, professional programs do hijack the systems calls. That would be the proper way to solve this issue. But I haven't had the motivation to code a solution. See http://stackoverflow.com/questions/1317067/windows-dns-hooks

**Comment by axxName** [comment]
script  dns_setup.bat installs  Google server first

`
REM Set fixed DNS server (Google) and KadNode as second

netsh interface ipv4 add dns name="!adapterName!" 8.8.8.8 index=1 validate=no
netsh interface ipv4 add dns name="!adapterName!" 127.0.0.1 index=2 validate=no
`

google DNS doesn't know about our .p2p domain
after negative response from Google DNS, Windows doesn't try to use next DNS server

**Comment by axxName** [comment]
Hmmm. Strange.
After restart of kadnode service only 127.0.0.1 in DNS list.
I added 8.8.8.8 
Now all works fine - my.p2p domain and Interrnet DNS resolves
......
in testWindows 
.....
I think I broke my work Windows 
I bag Your pardon. 

Thanks!

**Comment by mwarning** [comment]
Does it work the way it is? Or does something need to be changed.

**Comment by axxName** [comment]
I need time to fix my Windows.
Then I perform the tests

**Comment by axxName** [comment]
OK. I did tests.
It can't work this way.
As I understand how DNS clients work, it should be one DNS server on "localhost"   "::1" or "127.0.0.1"
it must serve  .p2p domain and it must make requests to external DNS servers for all other domains.

I guess around here in src/ext-dns.c

-------
line 601:
	/* Check if hostname ends with .p2p */
		if( !is_suffix( hostname, gconf->query_tld ) ) {
			return;
}
-------

and lookup code like this function  ngethostbyname()
http://www.binarytides.com/dns-query-code-in-c-with-linux-sockets/

**Comment by mwarning** [comment]
From what you tell, it looks to me like the windows behavior has changed (maybe in Windows 10?). But Implementing a reverse proxy in KadNode is a major task. We may need to investigate other options, if possible.

**Comment by axxName** [comment]
I have done tests on Windows 7, IPv4
I think DNS clients work the same in linux, in Windows(XP,7,10), etc...

**Comment by mwarning** [comment]
Then we need a different approach.

**Comment by mwarning** [comment]
@axxName putting the google dns second should work, no?
I am still a bit confused about what works for you and what not. :)

**Comment by axxName** [comment]
About Your DNSproxy code:

it would be better if this code will be enabled by default, if compiled with DNS option,
or will be activated if --dns-port option used
And use GoogleDNS by default if no (--dns-server) option is used

**Comment by mwarning** [comment]
The DNS proxy code is already compiled in when the DNS interface is compiled in.
The proxy will be enabled when --dns-server is specified.

We can set --dns-server in the configuration provided in the packages. External resources like 8.8.8.8 should not be present in the code itself.

**Comment by axxName** [comment]
OK.
Then you need to add comments about this in the README and in the default config.txt

**Comment by mwarning** [comment]
I would put it into the package configuration. Apart from that, we only need this proxy functionality for windows right now. On Debian systems we have nsswitch functionality and on openwrt we have dnsmasq filtering top level domains for us.

Tough the configuration can use some improvement.

**Comment by axxName** [comment]
Thank you. It is a good result!
