### ISSUE TITLE
configure amount of cached dns records

### ISSUE THREAD

**Issue by christf** [mwarning/KadNode#63]
is there a way of configuring the buffer size for the dns records?
I am considering running kadnode as a dns cache on freifunk nodes and having one program to do dns instead of two (dnsmasq and kadnode) would be better.

**Comment by mwarning** [comment]
hi christf, KadNode has no cache for its DNS interface or DNS proxy functionality.
It only caches queries for .p2p domains (those who are resolved using the DHT).

If it helps, you can configure dnsmasq to forward all *.p2p requests to KadNode. See https://github.com/mwarning/KadNode/wiki
