### ISSUE TITLE
lookup on wildcard does not seem to work

### ISSUE THREAD

**Issue by christf** [mwarning/KadNode#64]
I have two kadnode instances running with a custom tld called ".ffffm" 
the value-ids are tcs1.ffffm and tcs2.ffffm. using 
kadnode-ctl lookup tcs1.ffffm or kadnode-ctl lookup tcs2.ffffm I will receive a reply with an IP-Address however running a wildcard lookup like
kadnode-ctl lookup "*.ffffm" I am not receiving a result but seeing "Search in progress" for minutes already.

What should I do to investigate?

**Comment by mwarning** [comment]
kadnode-ctl lookup "*.ffffm" won't work.
It is like entering *.de in a browser. :-)

Let me know if the documentation is need to be improved.
