### ISSUE TITLE
lookup node expiration

### ISSUE THREAD

**Issue by axxName** [mwarning/KadNode#66]
I found in Your code that kad_lookup value is updated after 10 minutes.
kad.c
`if( results_entries_count( results ) == 0 ||
			(time_now_sec() - results->start_time) > (MAX_SEARCH_LIFETIME / 2)
) {`
Good Idea!

But in results.c
`void results_expire( void ) {
         if( results->start_time < (now - MAX_SEARCH_LIFETIME) ) {
                 results_remove( results );`

You remove search results after 20 minutes.
And a new search request, on demand takes some time.
It is not comfortable for desktop use, for example in browser.

Maybe to do remove_results_time 1 day or even 3 days?

**Comment by mwarning** [comment]
The idea behind this short period was that KadNode would only prevent new searches as long the result would be valid. The lifetime of an entry in the DHT network is about 20 min by most implementations.

If we increase the lifetime, the search result buffer would also need to be increased. Otherwise the search would be blocked.

An idea might be to cache, let's say, the last 32 searches for the whole runtime of KadNode. If an entry is in the cache, that results are returned, but if is the search is also >10min old, the search is also restarted.

**Comment by axxName** [comment]
Good idea! Can you implement it?

**Comment by mwarning** [comment]
I won't resist if you like to do it. :)
Otherwise, I can give it a try around Easter.

**Comment by axxName** [comment]
I am not professional programmer.
I will wait and hope. :)

**Comment by axxName** [comment]
if the mountain will not come to Mohammed, Mohammed must go to the mountain
;)

**Comment by mwarning** [comment]
I haven't forgotten this issue. I am still on a trip. :-)

**Comment by axxName** [comment]
I've made pull request.
Have a good trip!

**Comment by mwarning** [comment]
@axxName ah, great! But you shouldn't put other stuff in the merge request that does not belong there. Just make separate merge requests, even if it is a single line.
Otherwise things might get stalled by a minor issue that does not have anything to do with the ticket.

**Comment by axxName** [comment]
about new code  in results: keep all results in a ring buffer
compiled fine, but after starting kadnode daemon   - segmentation fault

**Comment by mwarning** [comment]
sorry about that. I will fix it later this evening.

**Comment by axxName** [comment]
about segfault fix:
It works now, but....
From first start (kadnode on sever and on client) it works fine and keeps results long time.
But, if restart kadnode on client side it takes much time and no lookup results, even if there is much entries in peers.txt

#kadnode-ctl status
DHT Searches: 0 active, 1 completed (max 1024)
...no lookup results here...

and after some time
#kadnode-ctl status
DHT Searches: 0 active, 0 completed (max 1024)

**Comment by axxName** [comment]
perhaps this problems on my local network
Tomorrow will do other tests

**Comment by axxName** [comment]
Uffff... New code works fine.
Thanks!


Another thought:
lookup search starts from first request from browser.
It takes some time.
Will be more comfortable if kadnode will do one lookup when starting daemon.
Then desktop will rapidly ready to browsing or VPN connect
It's difficult to do?

**Comment by mwarning** [comment]
hi @axxName,  KadNode does not store its previous lookups/results on shutdown.

**Comment by axxName** [comment]
the idea is not to save previous lookups
just start finding our server side kadnode when starting kadnode on client

**Comment by mwarning** [comment]
Not sure what you mean. When KadNode starts, it will load the peer list and start finding new peers.

**Comment by axxName** [comment]
I have on client side:
--value-id myhost.p2p
--auth-add-pkey myhost.p2p:xxxxxxxxxxxxxxxx


myhost.p2p will be resolvable when(~30sec) after starting kadnode daemon?
or
myhost.p2p will be resolvable when(~30sec) only after first request: nslookup myhost.p2p ?

**Comment by mwarning** [comment]
My guess would be around 15 seconds after start. But I haven't done recent testing.
I will code this ticket as there is a new release (for testing..).
