### ISSUE TITLE
KadNode as a library

### ISSUE THREAD

**Issue by chriamue** [mwarning/KadNode#70]
Is it possible that this project serves a library to include in other projects.
I really would like to use it for example in chat applications to 
resolve ip by public key as 'dns' .

**Comment by mwarning** [comment]
It is not possible yet, but I would love to do it and will give it a shoot very soon.
The project has recently been rewritten and I currently prepare the new release (packaging, testing etc.).

**Comment by chriamue** [comment]
I've already created some cmake projects based on this cmake template (https://github.com/cginternals/cmake-init) which also has packaging for deb and rpm.
Let me know if I can help anyhow.

**Comment by mwarning** [comment]
Thanks, but that would be too much of a change right now.
Anyway, how do you like the library to operate?
- kadnode, just as a library?
- how should the API look like?

So far this is the first API method I came up with:
int kadnode_lookup( const char query[], IP addr_array[], size_t addr_num );

How should settings be provided?

**Comment by mwarning** [comment]
Also important, how should the (non-blocking) event loop be integrated?
Maybe the library should utilize its own thread.

**Comment by chriamue** [comment]
I plan to provide to config as strings, not as file.
For my own I would run the event loop in my own thread, but for convenience the library should
additionally have its own thread.

Here is an example how I would like to use it. https://github.com/hyphaproject/hypha/blob/namesystem/source/utils/source/namesystem.cpp

**Comment by mwarning** [comment]
I think it good practice to not do threading in the library.
Some people want to use pthreads or other libs that might not be compatible.
Your example looks about right. Might take a few days to implement something usable.

**Comment by mwarning** [comment]
Library support won't make it into 2.0.0. There is too much work to be done. It will be a testing release anyway.

**Comment by melroy89** [comment]
I'm still interested in this. If there is a library, be sure to create Language binding to C++ but also other languages most likely.

**Comment by mwarning** [comment]
Sorry, no time to create and support a library right now.
