### ISSUE TITLE
Use multicast DNS discovery

### ISSUE THREAD

**Issue by mwarning** [mwarning/KadNode#81]
this is a more common protocol to discover peer partners

**Comment by stokito** [comment]
Is this about LPD? On the [Torrent BEPs list](https://www.bittorrent.org/beps/bep_0000.html) there are two deferred BEPs
* [Zeroconf Peer Advertising and Discovery](https://www.bittorrent.org/beps/bep_0026.html)
* [BitTorrent Local Tracker Discovery Protocol](https://www.bittorrent.org/beps/bep_0022.html)

Can they be useful?

**Comment by mwarning** [comment]
Local Peer Discovery (LPD) send a simple packer to the multicast addresses 239.192.152.143 and ff15::efc0:988f (see https://en.wikipedia.org/wiki/Local_Peer_Discovery).
But reading the actual code, I see that KadNode sends and parses "DHT <port>" , which is not the HTTP format that is described in BEP-14. I do not remember why the HTTP fomat is not used, it should be easy enough to be implemented.

EDIT: The peer discovery is for the BitTorrent part, so we can see that the address where the BitTorrent client is running. But the port is that of the BitTorrent client part and not the DHT!

**Comment by mwarning** [comment]
Other peer discovery protocols were no implemented to reduce the amount of complexity.
