### ISSUE TITLE
Dynamic is address

### ISSUE THREAD

**Issue by gedw99** [mwarning/KadNode#82]
Can this work where most of the nodes are home users or mobiles on dynamic want IP addresses ?

**Comment by gedw99** [comment]
Ok 10 minutes. good to know.

For me its way too slow. I was thinking of a global user to ip address routing table.
When a users IP changes ( apple actually pings an external endpoint to work it out. works but gludgy), then tell the global router, and it will broadcast it.  Now the ONLY way to broadcast to 1,000 of devices that have constantly changing IP addresses is to use websockets maybe ?
Should be 1 sec delay then.
When a device connects to the network. if we have a time time stamp on all user record data changes, then just send that use a list of all that changed ?

I guess this is getting away from the way DHT etc really works... I just was figuring the logic out above to illustrate how i would get a 1 sec delay.

Does not help does it ?

**Comment by gedw99** [comment]
https://github.com/libp2p

Has some libs that shoudl work ?

**Comment by mwarning** [comment]
Having a global user=>ip database sounds like a DNS server. :-) 

libp2p is probably way too big for wireless routers.

The IP address update could be improved by watching if the local IP address changes.
That would bring down the update time to maybe 10 seconds.
