### ISSUE TITLE
Move to Gitlab?

### ISSUE THREAD

**Issue by danger89** [mwarning/KadNode#83]
Github is acquired by Micro$oft.
https://www.theverge.com/2018/6/3/17422752/microsoft-github-acquisition-rumors

**Comment by drawkula** [comment]
We need a real P2P solution for "this problem".

**Comment by mwarning** [comment]
I consider moving to gitlab, but for now I will wait and see.

**Comment by mwarning** [comment]
I do not feel like switching now.

**Comment by mwarning** [comment]
hm, I see a login page. To have to login might not be good idea for open source projects.

**Comment by drawkula** [comment]
[GitLab](https://gitlab.com) cuddles with a data kraken: https://about.gitlab.com/2018/04/05/gke-gitlab-integration/

:-(

**Comment by mwarning** [comment]
"explore" is rather hidden. Even then, you see an empty trending list.
You might want to rearrange the stuff if possible.

**Comment by danger89** [comment]
I don't care for now, I mainly use it for myself.

**Comment by mwarning** [comment]
ok
