### ISSUE TITLE
Can't compile. mbedtls functions

### ISSUE THREAD

**Issue by axxName** [mwarning/KadNode#84]
`src/ext-tls-client.c: In function 'tls_client_get_id':
src/ext-tls-client.c:213:3: warning: implicit declaration of function 'mbedtls_sha256_update_ret' [-Wimplicit-function-declaration]
   mbedtls_sha256_update_ret(&ctx, (uint8_t*) &query[0], strlen(query));
   ^~~~~~~~~~~~~~~~~~~~~~~~~
src/ext-tls-client.c:214:3: warning: implicit declaration of function 'mbedtls_sha256_finish_ret' [-Wimplicit-function-declaration]
   mbedtls_sha256_finish_ret(&ctx, hash);
   ^~~~~~~~~~~~~~~~~~~~~~~~~
`

in mbedtls headers I see only 
mbedtls_sha256_update
and
mbedtls_sha256_finish
functions

**Comment by mwarning** [comment]
yes, that mbedtls_sha256_update and mbedtls_sha256_finish are going to be deprecated in newer mbedtls releases. A compile time check for the mbedtls would be a good solution... in progress.

**Comment by mwarning** [comment]
fixed in https://github.com/mwarning/KadNode/commit/0ea13be9c226bafe15035f838e87c337430a453b
