### ISSUE TITLE
How to configure /etc/nsswitch.conf?

### ISSUE THREAD

**Issue by zciendor** [mwarning/KadNode#87]
Any hint/pointer/documentation on how to configure `/etc/nsswitch.conf` so it makes use of `kadnode`? I just see that the daemon creates a socket under `/tmp/kadnode/kadnode_nss.sock` but that doesn't mean it works out-of-the-box, right?

**Comment by mwarning** [comment]
/tmp/kadnode/kadnode_nss.sock is for the kadnode nss module to connect to the kadnode daemon.
Have a look at what `make install` would do. At kadnode to the `host:` line and place build/libnss_kadnode.so.2 to /lib (there should be other libnss_*.so files).

**Comment by zciendor** [comment]
I didn't use `make install` but `dpkg-buildpackage -b -rfakeroot -us -uc` instead and then installed the resulting Debian package. However, the package contains the `libnss_kadnode.so.2` file.

So you mean the pure presence of this file is enough? No additional configuration required in `/etc/nsswitch.conf`?

```
$ dpkg-query -L kadnode
/.
/etc
/etc/init.d
/etc/init.d/kadnode
/etc/kadnode
/etc/kadnode/kadnode.conf
/etc/kadnode/peers.txt
/lib
/lib/arm-linux-gnueabihf
/lib/arm-linux-gnueabihf/libnss_kadnode-2.0.so
/lib/systemd
/lib/systemd/system
/lib/systemd/system/kadnode.service
/usr
/usr/bin
/usr/bin/kadnode
/usr/share
/usr/share/doc
/usr/share/doc/kadnode
/usr/share/doc/kadnode/changelog.Debian.gz
/usr/share/doc/kadnode/changelog.gz
/usr/share/doc/kadnode/copyright
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/kadnode-ctl.1.gz
/usr/share/man/man1/kadnode.1.gz
/lib/arm-linux-gnueabihf/libnss_kadnode.so.2
/usr/bin/kadnode-ctl
```

**Comment by mwarning** [comment]
The /etc/nsswitch.conf need to be configured.
I had to remove the code, since the debian package policies don't what the package to modify /etc/nsswitch.conf.

Maybe I should put it back and not try to publish kadnode via the debian repository.

**Comment by zciendor** [comment]
> The /etc/nsswitch.conf need to be configured.
That's what I thought and I was wondering how? How should the line(s) look like I have to add there?

Although I just noticed, that the regular `ping` command seems to work with `.p2p` addresses. I didn't touch `/etc/nsswitch.conf` at all yet. Still it seems to work automagically.

```

**Comment by mwarning** [comment]
hm, I do not know why it woks without an entry in /etc/nsswitch.conf.
Usually I would modify the /etc/nsswitch.conf to contain `kadnode` before `dns`.
```
hosts: files mymachines mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] kadnode dns myhostname
```

**Comment by zciendor** [comment]
> hm, I do not know why it works without an entry in /etc/nsswitch.conf.
At least it works for `.p2p` addresses I had already looked up manually via `kadnode-ctl lookup`. Maybe the results are cached somewhere...

**Comment by zciendor** [comment]
No sorry. I just realized my `/etc/nsswitch.conf` already contains the needed entry:
```
hosts:          files kadnode dns myhostname
```

But it wasn't me. So it must have been the Debian package which modified it during installation.

**Comment by mwarning** [comment]
Own announcements are cached in the  latest release, but not anymore in master.
Lookup results are cached. If a lookup is done after the half of the lifetime of the cache entry, the cached result will be returned, but a new request is triggered to revalidate/update the cached entry.

**Comment by zciendor** [comment]
> Maybe I should put it back and not try to publish kadnode via the debian repository.

I think it's fine if users know they have to add the string `kadnode` manually to `/etc/nsswitch.conf` `hosts line`. It's just not mentioned yet in the [FAQ](https://github.com/mwarning/KadNode/blob/master/misc/faq.md) nor [Manual](https://github.com/mwarning/KadNode/blob/master/misc/manpage.md), why I was wondering how it should work.

Thanks for the help!

**Comment by mwarning** [comment]
I will add it, thanks for mentioning  :-)

**Comment by mwarning** [comment]
ok, added to the manual.
@zciendor if Kadnode works for you now, I can do another release.

**Comment by zciendor** [comment]
That would be great! We want to include KadNode with the `zHIVErbox` distribution by default, but prefer to compile the latest stable release instead of `master`.
