### ISSUE TITLE
kadnode --bob-create-key file permissions

### ISSUE THREAD

**Issue by zciendor** [mwarning/KadNode#88]
`kadnode --bob-create-key` creates the resulting private key file with read permission **for everybody** (group and others). I suggest this is fixed so that the file is **only readable by the user** who ran this command.

**Comment by mwarning** [comment]
good idea!

**Comment by mwarning** [comment]
done https://github.com/mwarning/KadNode/commit/60c3380c35379887da720e49e76135a37f5f1c47
