### ISSUE TITLE
Cannot compile in cygwin 

### ISSUE THREAD

**Issue by lostfile** [mwarning/KadNode#99]
Ive installed all of the dependencies inside cygwin and it still fails to compile i will edit this issue later and show you the error messages i get

**Comment by mwarning** [comment]
ok, I haven't build kadnode with cygwin for quite a while.
But it's documented: https://github.com/mwarning/KadNode/tree/master/windows

**Comment by lostfile** [comment]
make
cc -Os -Wall -Wwrite-strings -pedantic -std=gnu99 -I/usr/local/include  -DLPD -DBOB -DCMD -g -DDEBUG -DDNS -DNSS -DTLS -c -o build/main.o src/main.c
cc -Os -Wall -Wwrite-strings -pedantic -std=gnu99 -I/usr/local/include  -DLPD -DBOB -DCMD -g -DDEBUG -DDNS -DNSS -DTLS -c -o build/searches.o src/searches.c
cc -Os -Wall -Wwrite-strings -pedantic -std=gnu99 -I/usr/local/include  -DLPD -DBOB -DCMD -g -DDEBUG -DDNS -DNSS -DTLS -c -o build/kad.o src/kad.c
cc -Os -Wall -Wwrite-strings -pedantic -std=gnu99 -I/usr/local/include  -DLPD -DBOB -DCMD -g -DDEBUG -DDNS -DNSS -DTLS -c -o build/log.o src/log.c
cc -Os -Wall -Wwrite-strings -pedantic -std=gnu99 -I/usr/local/include  -DLPD -DBOB -DCMD -g -DDEBUG -DDNS -DNSS -DTLS -c -o build/conf.o src/conf.c
cc -Os -Wall -Wwrite-strings -pedantic -std=gnu99 -I/usr/local/include  -DLPD -DBOB -DCMD -g -DDEBUG -DDNS -DNSS -DTLS -c -o build/net.o src/net.c
cc -Os -Wall -Wwrite-strings -pedantic -std=gnu99 -I/usr/local/include  -DLPD -DBOB -DCMD -g -DDEBUG -DDNS -DNSS -DTLS -c -o build/utils.o src/utils.c
cc -Os -Wall -Wwrite-strings -pedantic -std=gnu99 -I/usr/local/include  -DLPD -DBOB -DCMD -g -DDEBUG -DDNS -DNSS -DTLS -c -o build/announces.o src/announces.c
cc -Os -Wall -Wwrite-strings -pedantic -std=gnu99 -I/usr/local/include  -DLPD -DBOB -DCMD -g -DDEBUG -DDNS -DNSS -DTLS -c -o build/peerfile.o src/peerfile.c
cc -Os -Wall -Wwrite-strings -pedantic -std=gnu99 -I/usr/local/include  -DLPD -DBOB -DCMD -g -DDEBUG -DDNS -DNSS -DTLS -c -o build/unix.o src/unix.c
cc -Os -Wall -Wwrite-strings -pedantic -std=gnu99 -I/usr/local/include  -DLPD -DBOB -DCMD -g -DDEBUG -DDNS -DNSS -DTLS -c -o build/windows.o src/windows.c
src/windows.c: In function ‘windows_service_start’:
src/windows.c:72:3: warning: implicit declaration of function ‘log_warn’; did you mean ‘log_warning’? [-Wimplicit-function-declaration]
   log_warn("WIN: Can not start service: Error %d", GetLastError());
   ^~~~~~~~
   log_warning
cc -Os -Wall -Wwrite-strings -pedantic -std=gnu99 -I/usr/local/include  -DLPD -DBOB -DCMD -g -DDEBUG -DDNS -DNSS -DTLS -c -o build/ext-lpd.o src/ext-lpd.c
cc -Os -Wall -Wwrite-strings -pedantic -std=gnu99 -I/usr/local/include  -DLPD -DBOB -DCMD -g -DDEBUG -DDNS -DNSS -DTLS -c -o build/ext-bob.o src/ext-bob.c
cc -Os -Wall -Wwrite-strings -pedantic -std=gnu99 -I/usr/local/include  -DLPD -DBOB -DCMD -g -DDEBUG -DDNS -DNSS -DTLS -c -o build/ext-cmd.o src/ext-cmd.c
src/ext-cmd.c: In function ‘cmd_client’:
src/ext-cmd.c:431:53: error: ‘tv’ undeclared (first use in this function); did you mean ‘tm’?
   size = select_read(sock, buffer, strlen(buffer), &tv);
                                                     ^~
                                                     tm
src/ext-cmd.c:431:53: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:82: build/ext-cmd.o] Error 1

**Comment by mwarning** [comment]
Thanks for the report. I pushed two commits that should fix the issue.

**Comment by lostfile** [comment]
np

**Comment by mwarning** [comment]
ok, on to the next issue. :-)
